#!/bin/bash
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 1e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 5e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 3e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 8e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small.json --lr 1e-4
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 1e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 5e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 3e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 8e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium.json --lr 1e-4
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 1e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 5e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 3e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 8e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large.json --lr 1e-4
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 1e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 5e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 3e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 8e-5
python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 1e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 5e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 3e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 8e-5
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 1e-4
python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge.json --lr 1e-4
##############################################################
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 1e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 5e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 3e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 8e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_small_BT.json --lr 1e-4
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 1e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 5e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 3e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 8e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_medium_BT.json --lr 1e-4
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 1e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 5e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 3e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 8e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_large_BT.json --lr 1e-4
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 1e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 5e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 3e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 8e-5
#python train.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/DistilBERT/watches/config_watches_xlarge_BT.json --lr 1e-4