#!/bin/bash
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 1e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 5e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 3e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 8e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small.json --lr 1e-4
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 1e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 5e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 3e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 8e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium.json --lr 1e-4
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 1e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 5e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 3e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 8e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large.json --lr 1e-4
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 1e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 5e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 3e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 8e-5
python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 1e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 5e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 3e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 8e-5
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 1e-4
python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge.json --lr 1e-4
##############################################################
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 1e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 5e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 3e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 8e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_small_BT.json --lr 1e-4
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 1e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 5e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 3e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 8e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_medium_BT.json --lr 1e-4
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 1e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 5e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 3e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 8e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_large_BT.json --lr 1e-4
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 1e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 5e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 3e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 8e-5
#python train.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 1e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 5e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 3e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 8e-5
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 1e-4
#python train_random.py --device $1 -c configs/RoBERTa/cameras/config_cameras_xlarge_BT.json --lr 1e-4